package global

enum class Setting {

    // BOOLEANS
    PREDRAW,
    PREDRAW_OUTLINE,
    PREDRAW_SHOW_BEST,
    ALLOW_COLLISION,
    TRUE_COLOR,
    TRANSPARENT_TRIANGLES,
    SEQUENTIAL,

    // INTEGERS
    BLOCKS_WIDE,
    MAX_TRIANGLES,
    SAMPLES,
    THREAD_COUNT,
    REPAINT_WAIT_MS,
    ATTEMPTS,
    RANDOM_BLOCKS,

    // DOUBLES
    SCALE,
    POST_SCALE
}